#!/bin/bash

source me
source term
source types
source err

somando
function soma(){
	#     calll		ER FC       MSG         PARAM 			 VALUE
	#               $1 $2        $3          $4     		  $5
	error_exit $lnum $fname 
	#error_exit $lnum $fname
	#error_exit $(eval $trfname_int_positive param_txt_color "fdfdf"
}

soma
